new
w3schools-test/w3schools-test.github.io pull request #126
Opened 2021-07-15 18:32 UTC by savgym

2021-07-15 18:33 UTC, savgym commented
new

2021-07-15 18:33 UTC, savgym commented
new

2021-08-02 08:39 UTC, w3schools-test approved these changes
Please keep commits to the index.html page only :)

2021-08-02 08:45 UTC, w3schools-test requested changes
Please keep commits to the index.html page only :)

2021-08-02 08:54 UTC, closed without merging