add ignore
w3schools-test/w3schools-test.github.io pull request #1276
Opened 2022-12-11 07:06 UTC by Bhonegit

I made some changes

2022-12-11 07:07 UTC, Bhonegit commented
Making some changes

2022-12-12 07:41 UTC, w3schools-test requested changes
Please keep changes contained to the index.html file :)

2022-12-12 10:17 UTC, Bhonegit commented
Sending Message

2022-12-15 07:19 UTC, w3schools-test requested changes
Please keep changes contained to the index.html file, do not add additional files :)

2023-01-06 07:26 UTC, closed without merging