thanx w3
w3schools-test/w3schools-test.github.io pull request #2459
Opened 2023-11-24 12:09 UTC by MehmetBozkir

study study study

2023-11-24 12:11 UTC, MehmetBozkir reviewed
my comment

2023-11-27 08:10 UTC, w3schools-test requested changes
Please keep your changes contained to the specified area in index.html :)

2023-11-29 22:28 UTC, MehmetBozkir reviewed
Thanks

2023-11-29 22:29 UTC, MehmetBozkir commented
I hope the current size is suitable

2023-12-05 07:15 UTC, closed without merging