said hi
w3schools-test/w3schools-test.github.io pull request #2621
Opened 2024-01-22 18:08 UTC by mayaali6

2024-01-22 18:09 UTC, mayaali6 commented
gtr

2024-01-22 18:09 UTC, mayaali6 commented
rf

2024-01-22 18:15 UTC, mayaali6 commented
yyy

2024-01-24 07:26 UTC, w3schools-test requested changes
Please keep your changes contained to the specified area in index.html :)

2024-02-09 07:16 UTC, closed without merging